[package]
name = "fc"
version = "0.1.0"
authors = ["LeafChage <t.kusanagi5512@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
image="0.23.14"
bytes="1"
once_cell="1.9.0"
